spring:
  application:
    name: distributed-message-queue

server:
  port: ${broker.port}

broker:
  id: broker-1
  host: localhost
  port: 8080
  data-directory: data/broker-1

cluster:
  brokers:
    - id: broker-1
      host: localhost
      port: 8080
    - id: broker-2
      host: localhost
      port: 8081
    - id: broker-3
      host: localhost
      port: 8082

raft:
  election:
    min-timeout-millis: 1500
    max-timeout-millis: 3000
  heartbeat-interval-millis: 300
  transport:
    connect-timeout-millis: 1000
    read-timeout-millis: 2000
